SELECT
COUNT(*) COUNT
FROM
(
SELECT
IF(LENGTH(CONV(GENOTYPE, 10, 2)) < 4, LPAD(CONV(GENOTYPE, 10, 2),4, '0'), CONV(GENOTYPE, 10, 2)) AS GENOTYPE_CH
FROM ECOLI_DATA

) AS T
WHERE
SUBSTR(GENOTYPE_CH,-2,1) != '1'
AND (SUBSTR(GENOTYPE_CH,-1,1) = '1' OR SUBSTR(GENOTYPE_CH,-3,1) = '1')