-- 코드를 작성해주세요
# SELECT
#     I.ITEM_ID AS ITEM_ID,
#     I.ITEM_NAME AS ITEM_NAME,
#     I.RARITY AS RARITY
# FROM ITEM_INFO AS I
#     LEFT JOIN ITEM_TREE AS T
#         ON I.ITEM_ID = T.PARENT_ITEM_ID
# WHERE T.ITEM_ID IS NULL
# ORDER BY ITEM_ID DESC



SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
LEFT JOIN ITEM_TREE B ON A.ITEM_ID = B.PARENT_ITEM_ID
WHERE PARENT_ITEM_ID IS NULL
ORDER BY A.ITEM_ID DESC;