# SELECT *
# from (
#     select
#         SALES_DATE,
#         PRODUCT_ID,
#         USER_ID,
#         SALES_AMOUNT
#     FROM ONLINE_SALE
#     UNION ALL
#     SELECT
#         SALES_DATE,
#         PRODUCT_ID,
#         NULL as USER_ID,
#         SALES_AMOUNT
#     FROM OFFLINE_SALE
# ) as t1
#     WHERE t1.SALES_DATE like '2022-03%'
# ORDER BY SALES_DATE, PRODUCT_ID, USER_ID



# SELECT date_format(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT
# from ONLINE_SALE
# where sales_date like '2022-03%'
# UNION ALL
# select date_format(SALES_DATE,'%Y-%m-%d') SALES_DATE,PRODUCT_ID,NULL USER_ID,SALES_AMOUNT
# from OFFLINE_SALE
# where sales_date like '2022-03%'
# order by SALES_DATE, PRODUCT_ID, USER_ID

SELECT *
FROM
(SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
FROM ONLINE_SALE
UNION ALL
SELECT SALES_DATE, PRODUCT_ID, NULL, SALES_AMOUNT
FROM OFFLINE_SALE
) AS T1
WHERE T1.SALES_DATE >= '2022-03-01' AND T1.SALES_DATE <= '2022-03-31'
ORDER BY 1,2,3