SELECT * FROM (
SELECT CARS.CAR_ID AS CAR_ID
     , CARS.CAR_TYPE AS CAR_TYPE
     , FLOOR((1.00 - NVL(PLANS.DISCOUNT_RATE,0)/100)*30*CARS.DAILY_FEE) AS FEE 
  FROM CAR_RENTAL_COMPANY_CAR CARS   
 INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLANS
    ON (PLANS.CAR_TYPE = CARS.CAR_TYPE)
 WHERE CARS.CAR_ID NOT IN ( SELECT CAR_ID 
                              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                             WHERE (TO_CHAR(START_DATE,'YYYYMMDD') <= '20221130' AND TO_CHAR(END_DATE,'YYYYMMDD') >= '20221101')
                            )
  AND CARS.CAR_TYPE IN ('세단', 'SUV')
  AND PLANS.DURATION_TYPE = '30일 이상'
) X 
  WHERE X.FEE BETWEEN 500000 AND 2000000-1
  ORDER BY X.FEE DESC, X.CAR_TYPE, X.CAR_ID DESC