-- 코드를 입력하세요
# SELECT 
#     DISTINCT C.CAR_ID,
#     C.CAR_TYPE,
#     ROUND(C.DAILY_FEE * 30 * (100 - D.DISCOUNT_RATE) / 100,0) AS FEE
# FROM CAR_RENTAL_COMPANY_CAR AS C
#     LEFT JOIN (
#         SELECT *
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE
#             START_DATE <= '2022-11-30' AND
#             END_DATE >= '2022-11-01'
#         GROUP BY CAR_ID
#     ) AS H
#         ON C.CAR_ID = H.CAR_ID
#     JOIN (
#         SELECT CAR_TYPE, DISCOUNT_RATE
#         FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#         WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE LIKE '%30%'
#     ) AS D
#         ON C.CAR_TYPE = D.CAR_TYPE
# WHERE
#     C.CAR_TYPE IN ('세단', 'SUV') AND
#     30 * C.DAILY_FEE BETWEEN 500000 AND 2000000 AND
#     H.CAR_ID IS NULL
# GROUP BY C.CAR_ID
# ORDER BY FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC





WITH ## 2022-11-01~2022-11-30 까지 대여가능한 차량
ABLE_CAR AS (
SELECT  DISTINCT CAR_ID
  FROM  CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH
 WHERE  NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS R
    WHERE R.CAR_ID = CRH.CAR_ID
      AND R.START_DATE <= '2022-11-30'
      AND R.END_DATE >= '2022-11-01')
)
,
##30일 이상 할인율
DIS_PLAN AS(
SELECT  *
  FROM  CAR_RENTAL_COMPANY_DISCOUNT_PLAN
 WHERE  DURATION_TYPE = '30일 이상'
)


SELECT  AC.CAR_ID
        ,C.CAR_TYPE AS CAR_TYPE
        ,ROUND((C.DAILY_FEE * (1 - DP.DISCOUNT_RATE*0.01) * 30),0) AS FEE
  FROM  ABLE_CAR AS AC
  JOIN  CAR_RENTAL_COMPANY_CAR AS C
    ON  AC.CAR_ID = C.CAR_ID
  JOIN  DIS_PLAN AS DP
    ON  C.CAR_TYPE = DP.CAR_TYPE
 WHERE  C.CAR_TYPE IN ('SUV','세단') 
        AND (C.DAILY_FEE * (1 - DP.DISCOUNT_RATE*0.01) * 30) > 500000
        AND (C.DAILY_FEE * (1 - DP.DISCOUNT_RATE*0.01) * 30) < 2000000
 ORDER
    BY  FEE DESC, CAR_TYPE ASC, CAR_ID DESC
;