-- 코드를 입력하세요
# SELECT
#     FOOD_TYPE,
#     REST_ID,
#     REST_NAME,
#     FAVORITES
# FROM REST_INFO AS D
#     JOIN (
#         SELECT MAX(FAVORITES) AS MAX
#         FROM REST_INFO
#         GROUP BY FOOD_TYPE
#     ) AS M
#     ON D.FAVORITES = M.MAX
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC


SELECT 
R.FOOD_TYPE,R.REST_ID,R.REST_NAME,R.FAVORITES
FROM REST_INFO R JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) MAX_FAVORITE  FROM REST_INFO
GROUP BY FOOD_TYPE) T ON R.FOOD_TYPE = T.FOOD_TYPE AND R.FAVORITES = T.MAX_FAVORITE
ORDER BY  T.FOOD_TYPE DESC