-- 코드를 작성해주세요
# WITH C AS (
#     SELECT COUNT(*) AS COUNT
#     FROM ECOLI_DATA
# ), R AS (
#     SELECT
#         E.ID AS ID,
#         RANK() OVER(ORDER BY E.SIZE_OF_COLONY DESC) / C.COUNT AS PERCENT
#     FROM ECOLI_DATA AS E
#         JOIN C
# )

# SELECT
#     E.ID AS ID,
#     CASE
#         WHEN R.PERCENT <= 0.25 THEN 'CRITICAL'
#         WHEN R.PERCENT <= 0.5 THEN 'HIGH'
#         WHEN R.PERCENT <= 0.75 THEN 'MEDIUM'
#         WHEN R.PERCENT <= 1 THEN 'LOW'
#     END AS COLONY_NAME
# FROM ECOLI_DATA AS E
#     JOIN R
#         ON E.ID = R.ID
# ORDER BY E.ID



SELECT 
D.ID, 
CASE 
WHEN R <= 0.25 THEN 'CRITICAL'
WHEN R <= 0.50 THEN 'HIGH'
WHEN R <= 0.75 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME 
FROM (
    SELECT 
    ID, 
    PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS R
    FROM ECOLI_DATA
) D
ORDER BY D.ID;

# SELECT 
# D.ID,
# CASE
# WHEN D.R >= 0.75 THEN 'CRITICAL'
# WHEN D.R >= 0.5 THEN 'HIGH'
# WHEN D.R >= 0.25 THEN 'MEDIUM'
# ELSE 'LOW'
# END AS COLONY_NAME
# FROM (
#     SELECT 
#     ID,
#     PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY) AS R
#     FROM ECOLI_DATA
# ) D
# ORDER BY D.ID;