-- 코드를 입력하세요
SELECT
    U.USER_ID AS USER_ID,
    U.NICKNAME AS NICKNAME,
    CONCAT(U.CITY, ' ', U.STREET_ADDRESS1, ' ', U.STREET_ADDRESS2) AS '전체주소',
    CONCAT(LEFT(U.TLNO,3), '-', MID(U.TLNO,4,4), '-', RIGHT(U.TLNO,4)) AS '전화번호'
FROM USED_GOODS_USER AS U
    JOIN (
        SELECT WRITER_ID, COUNT(WRITER_ID) AS C
        FROM USED_GOODS_BOARD
        GROUP BY WRITER_ID
        HAVING COUNT(WRITER_ID) >= 3
    ) AS B
    ON U.USER_ID = B.WRITER_ID
ORDER BY B.WRITER_ID DESC