-- 코드를 입력하세요
# SELECT
#     ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID,
#     ANIMAL_OUTS.ANIMAL_TYPE AS ANIMAL_TYPE,
#     ANIMAL_OUTS.NAME AS NAME
# FROM ANIMAL_OUTS JOIN ANIMAL_INS
#     ON ANIMAL_OUtS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
# WHERE
#     ANIMAL_INS.SEX_UPON_INTAKE LIKE '%Intact%' AND
#     ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
# ORDER BY ANIMAL_OUTS.ANIMAL_ID ASC


SELECT C.ANIMAL_ID, C.ANIMAL_TYPE,C.NAME
FROM (SELECT B.ANIMAL_ID,B.ANIMAL_TYPE,B.NAME,B.SEX_UPON_OUTCOME
FROM ANIMAL_OUTS B JOIN ANIMAL_INS A ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE A.SEX_UPON_INTAKE like '%Intact%' AND (B.SEX_UPON_OUTCOME Like '%Spayed%' or B.SEX_UPON_OUTCOME like '%Neutered%')
) C
ORDER BY ANIMAL_ID