-- 코드를 입력하세요
SELECT
    ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID,
    ANIMAL_OUTS.ANIMAL_TYPE AS ANIMAL_TYPE,
    ANIMAL_OUTS.NAME AS NAME
FROM ANIMAL_OUTS JOIN ANIMAL_INS
    ON ANIMAL_OUtS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE
    ANIMAL_INS.SEX_UPON_INTAKE LIKE '%Intact%' AND
    ANIMAL_OUTS.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY ANIMAL_OUTS.ANIMAL_ID ASC


# SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
# FROM ANIMAL_OUTS
# WHERE ANIMAL_ID IN (
#     SELECT ANIMAL_ID
#     FROM ANIMAL_INS
#     WHERE SEX_UPON_INTAKE like 'Intact%'
# ) 
# AND SEX_UPON_OUTCOME IN ('Spayed', 'Neutered')
# ORDER BY ANIMAL_ID