/*SELECT R.REST_ID
     , I.REST_NAME
     , I.FOOD_TYPE
     , I.FAVORITES
     , I.ADDRESS
     , to_number(to_char(ROUND(AVG(R.REVIEW_SCORE), 2), 'fm9999999999999.00')) AS SCORE
  FROM REST_INFO   I
  JOIN REST_REVIEW R    ON I.REST_ID = R.REST_ID
 WHERE I.ADDRESS LIKE '서울%'
 GROUP BY R.REST_ID
     , I.REST_NAME
     , I.FOOD_TYPE
     , I.FAVORITES
     , I.ADDRESS
 ORDER BY AVG(R.REVIEW_SCORE) DESC, I.FAVORITES DESC*/
 
SELECT
         RI.REST_ID
        ,RI.REST_NAME
        ,RI.FOOD_TYPE
        ,RI.FAVORITES
        ,RI.ADDRESS
        ,to_number(TO_CHAR(ROUND(AVG(REVIEW_SCORE), 2), 'FM9990.00')) AS SCORE
FROM REST_INFO RI
    JOIN REST_REVIEW RR
ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY RI.REST_ID, RI.REST_NAME, RI.FOOD_TYPE ,RI.FAVORITES ,RI.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;