-- 코드를 입력하세요
# SELECT
#     I.REST_ID AS REST_ID,
#     I.REST_NAME AS REST_NAME,
#     I.FOOD_TYPE AS FOOD_TYPE,
#     I.FAVORITES AS FAVORITES,
#     I.ADDRESS AS ADDRESS,
#     ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
# FROM REST_INFO AS I
#     JOIN REST_REVIEW AS R
#         ON I.REST_ID = R.REST_ID
# WHERE I.ADDRESS LIKE '서울%'
# GROUP BY REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC

SELECT A. REST_ID as REST_ID, A.REST_NAME as REST_NAME, A.FOOD_TYPE as FOOD_TYPE, A.FAVORITES AS FAVORITES, A.ADDRESS AS ADDRESS, ROUND(AVG(B.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as A JOIN REST_REVIEW as B
on A.REST_ID=B.REST_ID
where A.ADDRESS LIKE '서울%'
group by REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
order by SCORE DESC, FAVORITES DESC