-- 코드를 입력하세요
SELECT
    YEAR(ONLINE_SALE.SALES_DATE) AS YEAR,
    MONTH(ONLINE_SALE.SALES_DATE) AS MONTH,
    USER_INFO.GENDER AS GENDER,
    COUNT(
        DISTINCT ONLINE_SALE.USER_ID,
        CASE WHEN USER_INFO.GENDER IS NOT NULL THEN 1 END
    ) AS USERS
FROM USER_INFO JOIN ONLINE_SALE
    ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
GROUP BY YEAR, MONTH, GENDER
HAVING GENDER IS NOT NULL
ORDER BY YEAR, MONTH, GENDER ASC