-- 코드를 입력하세요
-- SELECT ANIMAL_OUTS.ANIMAL_ID, ANIMAL_OUTS.NAME
-- FROM ANIMAL_OUTS LEFT JOIN ANIMAL_INS
--     ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
-- WHERE ANIMAL_INS.ANIMAL_ID IS NULL
-- ORDER BY ANIMAL_OUTS.ANIMAL_ID ASC


SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS O
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_INS)
ORDER BY O.ANIMAL_ID, O.NAME