WITH USER2021 AS(
    SELECT *
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') ='2021'
),
SALES2022 AS(
    SELECT *
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE,'YYYY') ='2022'
)

SELECT
    V.YEAR,
    V.MONTH,
    COUNT(DISTINCT V.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT V.USER_ID)/(
            SELECT COUNT(USER_ID)
            FROM USER2021),1
    ) AS PUCHASED_RATIO
FROM
    (
        SELECT 
            EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
            EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
            U.USER_ID AS USER_ID
        FROM SALES2022 O , USER2021 U
        WHERE O.USER_ID = U.USER_ID
    ) V
GROUP BY YEAR , MONTH
ORDER BY YEAR, MONTH;