/*WITH USER2021 AS(
    SELECT *
    FROM USER_INFO
    WHERE TO_CHAR(JOINED,'YYYY') ='2021'
),
SALES2022 AS(
    SELECT *
    FROM ONLINE_SALE
    WHERE TO_CHAR(SALES_DATE,'YYYY') ='2022'
)
SELECT
    YEAR,
    MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    to_number(to_char(ROUND(
        COUNT(DISTINCT USER_ID) /
        (
            SELECT COUNT(USER_ID)
            FROM USER2021
        ), 1
    ), 'FM9990.0')) AS PUCHASED_RATIO
FROM
    (
        SELECT
            EXTRACT(YEAR FROM SALES_DATE) YEAR,
            EXTRACT(MONTH FROM SALES_DATE) MONTH,
            U.USER_ID
        FROM SALES2022 O , USER2021 U
        WHERE O.USER_ID = U.USER_ID
    )
GROUP BY YEAR , MONTH
ORDER BY YEAR, MONTH;*/



WITH T1 AS (
SELECT
     TO_CHAR(B.SALES_DATE,'YYYY') AS YEAR,
     TO_CHAR(B.SALES_DATE,'FMMM') AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS COUNT_SALES
FROM USER_INFO A, ONLINE_SALE B 
WHERE TO_CHAR(A.JOINED, 'YYYY') ='2021' 
    AND A.USER_ID = B.USER_ID
GROUP BY TO_CHAR(B.SALES_DATE,'YYYY'), TO_CHAR(B.SALES_DATE,'FMMM')),
T2 AS
(SELECT COUNT(DISTINCT USER_ID) AS COUNT_INFO
 FROM USER_INFO
WHERE TO_CHAR(JOINED, 'YYYY') = '2021')

SELECt
    to_number(YEAR) as year,
    to_number(MONTH) as month,
    COUNT_SALES AS PURCHASED_USERS,
    ROUND(
        (COUNT_SALES/
         (SELECT COUNT_INFO
          FROM T2)),1) AS PUCHASED_RATIO
FROM T1
ORDER BY YEAR ASC, MONTH ASC;