-- 코드를 작성해주세요
WITH RECURSIVE GENERATION AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GEN
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT
        E.ID,
        E.PARENT_ID,
        G.GEN + 1 AS GEN
    FROM GENERATION AS G
        INNER JOIN ECOLI_DATA AS E
            ON G.ID = E.PARENT_ID
)


SELECT 
    COUNT(G.GEN) AS COUNT,
    G.GEN AS GENERATION
FROM ECOLI_DATA AS A
    LEFT JOIN ECOLI_DATA AS B
        ON A.ID = B.PARENT_ID
    JOIN GENERATION AS G
        ON A.ID = G.ID
WHERE B.ID IS NULL
GROUP BY GEN
ORDER BY GEN