-- 코드를 입력하세요

WITH TEMP AS (
SELECT
    CAR_ID,
    '대여중' AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
WHERE START_DATE <= TO_DATE('20221016', 'YYYYMMDD')
AND TO_DATE('20221016', 'YYYYMMDD') <= END_DATE
GROUP BY CAR_ID
ORDER BY CAR_ID
),
TEMP2 AS (
SELECT
    CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY B
GROUP BY CAR_ID
ORDER BY CAR_ID
)

SELECT
    CASE 
        WHEN T1.AVAILABILITY IS NULL THEN T2.CAR_ID
        ELSE T1.CAR_ID
    END AS CAR_ID,
    CASE
        WHEN T1.AVAILABILITY IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM TEMP T1, TEMP2 T2
WHERE T1.CAR_ID(+) = T2.CAR_ID
ORDER BY CAR_ID DESC