-- 코드를 입력하세요
# SELECT
#     O.CAR_ID AS CAR_ID,
#     IF(P.CAR_ID IS NULL, '대여 가능', '대여중') AS AVAILABILITY
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS O
#     LEFT JOIN (
#         SELECT CAR_ID
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE
#             START_DATE <= '2022-10-16' AND
#             END_DATE >= '2022-10-16'
#     ) AS P
#     ON O.CAR_ID = P.CAR_Id
# GROUP BY O.CAR_ID
# ORDER BY O.CAR_ID DESC


WITH B AS (
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16' AND END_DATE >= '2022-10-16'
)

SELECT A.CAR_ID,
       CASE 
           WHEN B.CAR_ID IS NULL THEN '대여 가능'
           ELSE '대여중'
       END AS "AVAILABILITY"
FROM (
        SELECT DISTINCT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        GROUP BY CAR_ID
     ) A
LEFT JOIN B
ON A.CAR_ID = B.CAR_ID
ORDER BY A.CAR_ID DESC;