-- -- 코드를 입력하세요
-- SELECT *
-- FROM (
-- SELECT 
--     A.NAME, A.DATETIME
-- FROM ANIMAL_INS A, ANIMAL_OUTS B
-- WHERE A.ANIMAL_ID = B.ANIMAL_ID(+)
-- AND B.ANIMAL_ID IS NULL
-- ORDER BY A.DATETIME
--     )
-- WHERE ROWNUM BETWEEN 1 AND 3
    


SELECT T.NAME AS NAME, T.DATETIME AS DATETIME
FROM
    (SELECT A.NAME AS NAME , A.DATETIME AS DATETIME
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID = B.ANIMAL_ID(+) and b.animal_id is NULL
    ORDER BY DATETIME ASC) T
WHERE ROWNUM <= 3;