-- 코드를 입력하세요
# SELECT RE.FLAVOR
# FROM (
#     SELECT *
#     FROM FIRST_HALF
#     UNION ALL
#     SELECT *
#     FROM JULY
#     ) AS RE
# GROUP BY RE.FLAVOR
# ORDER BY SUM(RE.TOTAL_ORDER) DESC
# LIMIT 3



SELECT a.FLAVOR
FROM FIRST_HALF a JOIN JULY b ON a.flavor = b.flavor
GROUP BY b.FLAVOR
ORDER BY (a.TOTAL_ORDER + SUM(b.TOTAL_ORDER)) DESC
LIMIT 3