-- 코드를 입력하세요
/*SELECT
    A.APNT_NO AS APNT_NO,
    P.PT_NAME AS PT_NAME,
    P.PT_NO AS PT_NO,
    A.MCDP_CD AS MCDP_CD,
    D.DR_NAME AS DR_NAME,
    A.APNT_YMD AS APNT_YMD
FROM PATIENT AS P
    JOIN APPOINTMENT AS A
        ON P.PT_NO = A.PT_NO
    JOIN DOCTOR AS D
        ON A.MDDR_ID = D.DR_ID
WHERE
    A.MCDP_CD = 'CS' AND
    A.APNT_YMD LIKE '2022-04-13%' AND
    A.APNT_CNCL_YN != 'Y'
ORDER BY APNT_YMD ASC*/



SELECT 
    A.APNT_NO,
    C.PT_NAME,
    C.PT_NO,
    A.MCDP_CD,
    B.DR_NAME,
    A.APNT_YMD
FROM APPOINTMENT A
JOIN DOCTOR B ON A.MDDR_ID = B.DR_ID
JOIN PATIENT C ON A.PT_NO = C.PT_NO
WHERE A.APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59'
  AND A.APNT_CNCL_YN != 'Y'
  AND A.MCDP_CD = 'CS'
ORDER BY A.APNT_YMD;