-- 코드를 입력하세요
/*SELECT
    A.APNT_NO AS APNT_NO,
    P.PT_NAME AS PT_NAME,
    P.PT_NO AS PT_NO,
    A.MCDP_CD AS MCDP_CD,
    D.DR_NAME AS DR_NAME,
    A.APNT_YMD AS APNT_YMD
FROM PATIENT AS P
    JOIN APPOINTMENT AS A
        ON P.PT_NO = A.PT_NO
    JOIN DOCTOR AS D
        ON A.MDDR_ID = D.DR_ID
WHERE
    A.MCDP_CD = 'CS' AND
    A.APNT_YMD LIKE '2022-04-13%' AND
    A.APNT_CNCL_YN != 'Y'
ORDER BY APNT_YMD ASC*/



SELECT a.APNT_NO, p.PT_NAME, p.PT_NO, a.MCDP_CD, d.DR_NAME, a.APNT_YMD
from APPOINTMENT a
join DOCTOR d on a.MDDR_ID = d.DR_ID
join PATIENT p on a.PT_NO = p.PT_NO
where a.APNT_CNCL_YN = 'N' and a.MCDP_CD = 'CS' and DATE(a.APNT_YMD) = '2022-04-13%'
order by APNT_YMD