-- 코드를 입력하세요
# SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d')
# FROM MEMBER_PROFILE
# WHERE MONTH(DATE_OF_BIRTH) = '03' AND GENDER = 'W' AND TLNO IS NOT NULL
# ORDER BY MEMBER_ID ASC

SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_FORMAT(DATE_OF_BIRTH,'%Y-%m-%d') FROM MEMBER_PROFILE
WHERE substr(DATE_OF_BIRTH, 6, 7)  = 03 AND GENDER = 'W' AND TLNO is NOT NULL
ORDER BY MEMBER_ID ASC