-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 20
GROUP BY HOUR
ORDER BY HOUR ASC

-- 코드를 입력하세요
# SELECT TO_CHAR(TO_CHAR(DATETIME, 'HH24'), '99') AS HOUR, 
#         COUNT(*) AS COUNT 
# FROM ANIMAL_OUTS 
# GROUP BY TO_CHAR(DATETIME, 'HH24')
# HAVING TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 19
# ORDER BY TO_CHAR(DATETIME, 'HH24');