-- 코드를 입력하세요
WITH RM AS (
    SELECT MEMBER_ID, COUNT(MEMBER_ID) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC
    LIMIT 1
)

SELECT
    M.MEMBER_NAME AS MEMBER_NAME,
    R.REVIEW_TEXT AS REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS M
    JOIN REST_REVIEW AS R
        ON M.MEMBER_ID = R.MEMBER_ID
    JOIN RM
        ON R.MEMBER_ID = RM.MEMBER_ID
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC