# WITH ReviewCounts AS (
#     SELECT MEMBER_ID, COUNT(*) AS review_count
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
# ),
# TopReviewers AS (
#     SELECT MEMBER_ID
#     FROM ReviewCounts
#     WHERE review_count = (SELECT MAX(review_count) FROM ReviewCounts)
# )

# SELECT 
#     MEMBER_NAME,
#     REVIEW_TEXT,
#     DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') as review_date
# FROM 
#     REST_REVIEW
#         JOIN 
#             TopReviewers ON rest_review.MEMBER_ID = topreviewers.MEMBER_ID
#         JOIN 
#             MEMBER_PROFILE ON rest_review.MEMBER_ID = member_profile.MEMBER_ID
# ORDER BY 
#     REVIEW_DATE, REVIEW_TEXT;



SELECT MP.MEMBER_NAME, REVIEW_TEXT, REVIEW_DATE
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
WHERE MP.MEMBER_ID IN (
SELECT RR.MEMBER_ID
FROM MEMBER_PROFILE AS MP
JOIN REST_REVIEW AS RR
ON MP.MEMBER_ID = RR.MEMBER_ID
GROUP BY RR.MEMBER_ID
HAVING COUNT(*) = 
    (SELECT COUNT(*) AS C
    FROM MEMBER_PROFILE AS MP
    JOIN REST_REVIEW AS RR
    ON MP.MEMBER_ID = RR.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1)
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT ASC;