/*SELECT
    C.ID AS ID,
    C.GENOTYPE AS GENOTYPE,
    P.GENOTYPE AS PARENT_GENOTYPE
FROM
    ECOLI_DATA AS C
        JOIN ECOLI_DATA AS P
            ON C.PARENT_ID = P.ID
                AND C.GENOTYPE & P.GENOTYPE = P.GENOTYPE
ORDER BY C.ID*/


SELECT 
A.ID, 
A.GENOTYPE,
B.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS A
JOIN ECOLI_DATA AS B
ON A.PARENT_ID = B.ID
WHERE A.GENOTYPE & B.GENOTYPE = B.GENOTYPE
ORDER BY A.ID;