-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_OUTS.NAME AS NAME
FROM ANIMAL_OUTS JOIN ANIMAL_INS
    ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
ORDER BY ANIMAL_INS.DATETIME ASC