-- 코드를 입력하세요
# SELECT ANIMAL_OUTS.ANIMAL_ID AS ANIMAL_ID, ANIMAL_OUTS.NAME AS NAME
# FROM ANIMAL_OUTS JOIN ANIMAL_INS
#     ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
# WHERE ANIMAL_OUTS.DATETIME < ANIMAL_INS.DATETIME
# ORDER BY ANIMAL_INS.DATETIME ASC


# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_INS AS A
# JOIN ANIMAL_OUTS AS B
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE B.DATETIME < A.DATETIME
# # WHERE DATEDIFF(B.DATETIME, A.DATETIME) < 0
# ORDER BY A.DATETIME


select i.animal_id, i.name
from animal_ins i join animal_outs o
on i.animal_id = o.animal_id
where i.datetime > o.datetime
order by i.datetime asc;