SELECT
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    ((
        SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA a
        WHERE YEAR(a.DIFFERENTIATION_DATE) = YEAR(b.DIFFERENTIATION_DATE)
    ) - b.SIZE_OF_COLONY) AS YEAR_DEV,
    b.ID
FROM ECOLI_DATA b
ORDER BY YEAR, YEAR_DEV