WITH B AS (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR,
        MAX(SIZE_OF_COLONY) AS MAX
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT 
    YEAR(E.DIFFERENTIATION_DATE) AS YEAR,
    (B.MAX - E.SIZE_OF_COLONY) AS YEAR_DEV,
    E.ID AS ID
FROM ECOLI_DATA AS E
    JOIN B
        ON YEAR(E.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV