-- 코드를 입력하세요
# SELECT FIRST_HALF.FLAVOR
# FROM FIRST_HALF JOIN ICECREAM_INFO
#     ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
# WHERE
#     ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based' AND
#     FIRST_HALF.TOTAL_ORDER > 3000
# ORDER BY FIRST_HALF.TOTAL_ORDER DESC


# SELECT FH.FLAVOR
# FROM ICECREAM_INFO AS IC JOIN FIRST_HALF AS FH ON IC.FLAVOR = FH.FLAVOR
# WHERE FH.TOTAL_ORDER > 3000 AND IC.INGREDIENT_TYPE LIKE 'fruit%'
# ORDER BY FH.TOTAL_ORDER DESC

SELECT A.FLAVOR
FROM FIRST_HALF  A
INNER JOIN ICECREAM_INFO B ON A.FLAVOR =B.FLAVOR
WHERE A.TOTAL_ORDER > 3000
AND   B.INGREDIENT_TYPE ='fruit_based'
ORDER BY A.TOTAL_ORDER DESC