-- 코드를 작성해주세요
/*WITH B AS (
    SELECT
        N.FISH_NAME AS NAME,
        N.FISH_TYPE AS TYPE,
        MAX(I.LENGTH) AS LEN
    FROM FISH_INFO AS I
        JOIN FISH_NAME_INFO AS N
            ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_TYPE, N.FISH_NAME
)

SELECT
    I.ID AS ID,
    B.NAME AS FISH_NAME,
    B.LEN AS LENGTH
FROM FISH_INFO AS I
    JOIN B
        ON I.FISH_TYPE = B.TYPE
WHERE I.LENGTH = B.LEN        
ORDER BY I.ID*/



SELECT A.ID,B.FISH_NAME, A.LENGTH
FROM FISH_INFO AS A
LEFT JOIN FISH_NAME_INFO B
ON A.FISH_TYPE = B.FISH_TYPE

WHERE LENGTH IN
(SELECT MAX(LENGTH)
FROM FISH_INFO AS F
WHERE F.FISH_TYPE = A.FISH_TYPE
GROUP BY F.FISH_TYPE)
AND LENGTH IS NOT NULL

ORDER BY A.ID ASC;