-- 코드를 작성해주세요
WITH B AS (
    SELECT
        N.FISH_NAME AS NAME,
        N.FISH_TYPE AS TYPE,
        MAX(I.LENGTH) AS LEN
    FROM FISH_INFO AS I
        JOIN FISH_NAME_INFO AS N
            ON I.FISH_TYPE = N.FISH_TYPE
    GROUP BY N.FISH_TYPE, N.FISH_NAME
)

SELECT
    I.ID AS ID,
    B.NAME AS FISH_NAME,
    B.LEN AS LENGTH
FROM FISH_INFO AS I
    JOIN B
        ON I.FISH_TYPE = B.TYPE
WHERE I.LENGTH = B.LEN        
ORDER BY I.ID