SELECT BOOK_ID, to_char(PUBLISHED_DATE, 'yyyy-mm-dd')
FROM BOOK
WHERE CATEGORY = '인문' 
    AND PUBLISHED_DATE BETWEEN TO_DATE('2021-01','YYYY-MM')
    AND TO_DATE('2021-12','YYYY-MM')
ORDER BY PUBLISHED_DATE ASC