-- 코드를 작성해주세요
WITH B AS (
    SELECT
        EMP_NO AS NO,
        SUM(SCORE) AS SCORE,
        RANK() OVER(ORDER BY SUM(SCORE) DESC) AS RANKING
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)

SELECT
    B.SCORE AS SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM HR_EMPLOYEES AS E
    JOIN B
        ON E.EMP_NO = B.NO
WHERE RANKING = 1