-- 코드를 입력하세요
 # SELECT
 #     B.TITLE,
 #     B.BOARD_ID,
 #     R.REPLY_ID,
 #     R.WRITER_ID,
 #     R.CONTENTS,
 #     DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
 # FROM USED_GOODS_BOARD AS B
 #     JOIN USED_GOODS_REPLY AS R
 #     ON B.BOARD_ID = R.BOARD_ID
 # WHERE B.CREATED_DATE LIKE '2022-10%'
 # GROUP BY B.BOARD_ID
 # ORDER BY R.CREATED_DATE, B.TITLE
 
 
 
 SELECT USED_GOODS_BOARD.TITLE, 
       USED_GOODS_BOARD.BOARD_ID, 
       USED_GOODS_REPLY.REPLY_ID, 
       USED_GOODS_REPLY.WRITER_ID, 
       USED_GOODS_REPLY.CONTENTS, 
       DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY
LEFT JOIN USED_GOODS_BOARD ON USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
WHERE (YEAR(USED_GOODS_BOARD.CREATED_DATE) = "2022") AND (MONTH(USED_GOODS_BOARD.CREATED_DATE) = "10")
ORDER BY USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE