-- SELECT A.TITLE
--      , A.BOARD_ID
--      , B.REPLY_ID
--      , B.WRITER_ID
--      , B.CONTENTS
--      , TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
--   FROM USED_GOODS_BOARD A JOIN USED_GOODS_REPLY B 
--     ON (A.BOARD_ID = B.BOARD_ID)
--  WHERE TO_CHAR(A.CREATED_DATE, 'YYYYMM')='202210'
--  ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;



SELECT A.TITLE, A.BOARD_ID, REPLY_ID,B.WRITER_ID,B.CONTENTS, to_char(B.CREATED_DATE, 'YYYY-MM-DD') as created_date
from USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B
on A.BOARD_ID = B.BOARD_ID
where  to_char(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
order by created_date asc, title asc