SELECT B.TITLE AS TITLE, RE.BOARD_ID AS BOARD_ID, RE.REPLY_ID AS REPLY_ID , RE.WRITER_ID AS WRITER_ID, RE.CONTENTS AS CONTENTS, TO_CHAR(RE.CREATED_DATE,'YYYY-MM-DD')AS CREATED_DATE
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY RE
WHERE B.BOARD_ID = RE.BOARD_ID
AND B.CREATED_DATE BETWEEN TO_DATE('2022-10-01','YYYY-MM-DD') AND TO_DATE('2022-10-31','YYYY-MM-DD')
ORDER BY RE.CREATED_DATE , B.TITLE ;