-- 코드를 입력하세요
WITH BOARD AS (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)

SELECT
    CONCAT('/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
    JOIN BOARD AS B
    ON F.BOARD_ID = B.BOARD_ID
ORDER BY F.FILE_ID DESC



# select concat('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) as FILE_PATH
# from
# USED_GOODS_FILE
# where board_id = (SELECT board_id
# FROM USED_GOODS_BOARD
# order by VIEWS desc
# limit 1)