-- SELECT '/home/grep/src/'||B.BOARD_ID||'/'||B.FILE_ID||FILE_NAME||FILE_EXT AS FILE_PATH
--   FROM (SELECT *
--         FROM (
--       SELECT BOARD_ID 
--       FROM USED_GOODS_BOARD 
--       ORDER BY VIEWS DESC
--       ) WHERE ROWNUM = 1
--   ) A
--   INNER JOIN USED_GOODS_FILE B
--   ON A.BOARD_ID = B.BOARD_ID
--   WHERE 1=1
--   ORDER BY B.FILE_ID desc


SELECT CONCAT(CONCAT(CONCAT(CONCAT(CONCAT('/home/grep/src/', A.BOARD_ID),'/'),B.file_id), B.FILE_NAME),B.file_ext) AS FILEPATH
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_FILE B
ON A.BOARD_ID = B.BOARD_ID
WHERE A.VIEWS = (
SELECT MAX(VIEWS)
FROM USED_GOODS_BOARD
)
order by b.file_id desc