# Select CATEGORY ,PRICE as MAX_PRICE ,PRODUCT_NAME
# from FOOD_PRODUCT
# where price in (select max(price) from FOOD_PRODUCT group by category) and (category = '과자' or category = '국'or category = '김치'or category = '식용유')
# group by category
# order by price desc



SELECT CATEGORY, PRICE AS MAXPRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE IN(
SELECT MAX(PRICE)
FROM FOOD_PRODUCT
GROUP BY CATEGORY)
GROUP BY CATEGORY
HAVING CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유'
ORDER BY 2 DESC;



# SELECT CATEGORY, PRICE AS MAXPRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE CATEGORY = '과자' OR CATEGORY = '국' OR CATEGORY = '김치' OR CATEGORY = '식용유' AND
# PRICE IN(
# SELECT MAX(PRICE)
# FROM FOOD_PRODUCT
# GROUP BY CATEGORY)
# GROUP BY CATEGORY
# ORDER BY 2 DESC;